name: Build Android App

on:
  push:
  # Need to figure out how to block direct pushes to these branches
    branches:
      - main
      - pre-release
  pull_request:
    branches:
      - main
      - pre-release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build Android App
      uses: sparkfabrik/android-build-action@v1.2.0
      with:
        output-path: AwareD.apk
